<template>
  <div>
    <svg>
      <defs>
        <marker
          id="m-end"
          markerWidth="10"
          markerHeight="10"
          refX="9"
          refY="3"
          orient="auto"
          markerUnits="strokeWidth"
        >
          <path d="M0,0 L0,6 L9,3 z"></path>
        </marker>
        <marker
          id="m-start"
          markerWidth="6"
          markerHeight="6"
          refX="-4"
          refY="3"
          orient="auto"
          markerUnits="strokeWidth"
        >
          <rect width="3" height="6"></rect>
        </marker>
      </defs>
    </svg>

    <d3-network
      ref="net"
      :net-nodes="nodes"
      :net-links="links"
      :options="options"
      :link-cb="lcb"
    />
  </div>
  <!-- <div class="title">
    <h1> <a href="https://github.com/emiliorizzo/vue-d3-network">vue-d3-network</a> </h1> 
    <ul class="menu">
      <li>
        <label> Node size  </label>
        <input type="range" min="1" max="100" v-model='nodeSize' /> {{ options.nodeSize }}
      </li>
      <li>
        <label>Render as  </label>
      <input type="radio" :value='false' v-model='canvas' />
      <label>SVG</label>
      <input type="radio" :value='true' v-model='canvas' />
      <label>Canvas</label>
      </li>  
    </ul>
    </div>
    <d3-network ref='net' :net-nodes="nodes" :net-links="links" :options="options" /> 
  </div>-->
  <!-- TEST -->
  <!-- <svg>
  <rect x="120" y="100" width="100" height="100" rx="15" />


</svg> -->
  <!-- <hierarchical-edge-bundling height="100%" identifier="id" :data="tree" :links="links" node-text="name"/> -->

  <!-- <tree :data="treeData" node-text="name" layoutType="circular" type="cluster" :key="treeKey">
      <template #node="{ data, node: { depth }, isRetracted }">
        <template v-if="data.children && data.children.length">
          <path :fill="isRetracted ? 'red' : 'blue'" d="M190.5..">
            <title>{{ data.text }} {{ depth }}</title>
          </path>
        </template>
        <template v-else>
          <circle r="6" :stroke="'blue' ? 'blue' : 'yellow'">
            <title>{{ data.text }} {{ depth }}</title>
          </circle>
        </template>
      </template>
      </tree>
      {{treeData}} -->
  <!-- </div> -->
</template>
    
  

<script>
import D3Network from "vue-d3-network";

export default {
  components: {
    D3Network,
  },
  // props: ["treeData"],
  // mounted: function () {
  // this.treeDataGraphed = this.treeData;
  // },
  data() {
    return {
      nodes: [
        { id: 1, name: "BiologicalEntity", _size: 30 },
        { id: 2, name: "BiologicalProcess" },
        { id: 3, name: "BiologicalProcessOrActivity" },
        { id: 4, name: "BiologicalSex" },
        { id: 5, name: "Cell" },
        { id: 6, name: "CellLine" },
        { id: 7, name: "CellularComponent" },
        { id: 8, name: "ChemicalEntity" },
        { id: 9, name: "ChemicalExposure" },
        { id: 10, name: "ChemicalMixture" },
        { id: 11, name: "ChemicalSubstance" },
        { id: 12, name: "ComplexChemicalMixture" },
        { id: 13, name: "ComplexMolecularMixture" },
        { id: 14, name: "Disease" },
        { id: 15, name: "Drug" },
        { id: 16, name: "Gene",  _size: 60},
        { id: 17, name: "GeneFamily" },
        { id: 18, name: "MolecularActivity" },
        { id: 19, name: "MolecularEntity" },
        { id: 20, name: "MolecularMixture" },
        { id: 21, name: "Pathway" },
        { id: 22, name: "PhenotypicFeature" },
        { id: 23, name: "PhenotypicQuality" },
        { id: 24, name: "PhysiologicalProcess" },
        { id: 25, name: "Polypeptide" },
        { id: 26, name: "Protein" },
        { id: 27, name: "SequenceFeature" },
        { id: 28, name: "SequenceVariant" },
        { id: 29, name: "SmallMolecule" },
        { id: 30, name: "Treatment" },
      ],
      links: [
        { sid: 29, tid: 29, _color: "black" },
        { sid: 29, tid: 16, _color: "black" },
        { sid: 16, tid: 29, _color: "black" },
        { sid: 16, tid: 16, _color: "black" },
        { sid: 16, tid: 14, _color: "black" },
        { sid: 14, tid: 16, _color: "black" },
        { sid: 28, tid: 14, _color: "black" },
        { sid: 14, tid: 28, _color: "black" },
        { sid: 28, tid: 16, _color: "black" },
        { sid: 16, tid: 28, _color: "black" },
        { sid: 14, tid: 14, _color: "black" },
        { sid: 5, tid: 25, _color: "black" },
        { sid: 25, tid: 5, _color: "black" },
        { sid: 29, tid: 14, _color: "black" },
        { sid: 14, tid: 29, _color: "black" },
        { sid: 25, tid: 25, _color: "black" },
        { sid: 25, tid: 16, _color: "black" },
        { sid: 16, tid: 25, _color: "black" },
        { sid: 29, tid: 25, _color: "black" },
        { sid: 25, tid: 29, _color: "black" },
        { sid: 25, tid: 14, _color: "black" },
        { sid: 14, tid: 25, _color: "black" },
        { sid: 7, tid: 25, _color: "black" },
        { sid: 25, tid: 7, _color: "black" },
        { sid: 5, tid: 24, _color: "black" },
        { sid: 24, tid: 5, _color: "black" },
        { sid: 16, tid: 5, _color: "black" },
        { sid: 5, tid: 16, _color: "black" },
        { sid: 25, tid: 24, _color: "black" },
        { sid: 24, tid: 25, _color: "black" },
        { sid: 7, tid: 5, _color: "black" },
        { sid: 5, tid: 7, _color: "black" },
        { sid: 18, tid: 5, _color: "black" },
        { sid: 5, tid: 18, _color: "black" },
        { sid: 29, tid: 7, _color: "black" },
        { sid: 7, tid: 29, _color: "black" },
        { sid: 16, tid: 24, _color: "black" },
        { sid: 24, tid: 16, _color: "black" },
        { sid: 5, tid: 29, _color: "black" },
        { sid: 29, tid: 5, _color: "black" },
        { sid: 25, tid: 18, _color: "black" },
        { sid: 18, tid: 25, _color: "black" },
        { sid: 22, tid: 14, _color: "black" },
        { sid: 14, tid: 22, _color: "black" },
        { sid: 24, tid: 14, _color: "black" },
        { sid: 14, tid: 24, _color: "black" },
        { sid: 7, tid: 18, _color: "black" },
        { sid: 18, tid: 7, _color: "black" },
        { sid: 5, tid: 14, _color: "black" },
        { sid: 14, tid: 5, _color: "black" },
        { sid: 29, tid: 24, _color: "black" },
        { sid: 24, tid: 29, _color: "black" },
        { sid: 7, tid: 7, _color: "black" },
        { sid: 16, tid: 7, _color: "black" },
        { sid: 7, tid: 16, _color: "black" },
        { sid: 5, tid: 5, _color: "black" },
        { sid: 29, tid: 22, _color: "black" },
        { sid: 22, tid: 29, _color: "black" },
        { sid: 24, tid: 24, _color: "black" },
        { sid: 18, tid: 16, _color: "black" },
        { sid: 16, tid: 18, _color: "black" },
        { sid: 29, tid: 18, _color: "black" },
        { sid: 18, tid: 29, _color: "black" },
        { sid: 18, tid: 14, _color: "black" },
        { sid: 14, tid: 18, _color: "black" },
        { sid: 7, tid: 24, _color: "black" },
        { sid: 24, tid: 7, _color: "black" },
        { sid: 25, tid: 22, _color: "black" },
        { sid: 22, tid: 25, _color: "black" },
        { sid: 8, tid: 14, _color: "black" },
        { sid: 14, tid: 8, _color: "black" },
        { sid: 22, tid: 22, _color: "black" },
        { sid: 8, tid: 5, _color: "black" },
        { sid: 5, tid: 8, _color: "black" },
        { sid: 25, tid: 8, _color: "black" },
        { sid: 8, tid: 25, _color: "black" },
        { sid: 16, tid: 22, _color: "black" },
        { sid: 22, tid: 16, _color: "black" },
        { sid: 8, tid: 16, _color: "black" },
        { sid: 16, tid: 8, _color: "black" },
        { sid: 7, tid: 14, _color: "black" },
        { sid: 14, tid: 7, _color: "black" },
        { sid: 18, tid: 24, _color: "black" },
        { sid: 24, tid: 18, _color: "black" },
        { sid: 24, tid: 22, _color: "black" },
        { sid: 22, tid: 24, _color: "black" },
        { sid: 15, tid: 14, _color: "black" },
        { sid: 14, tid: 15, _color: "black" },
        { sid: 18, tid: 18, _color: "black" },
        { sid: 8, tid: 7, _color: "black" },
        { sid: 7, tid: 8, _color: "black" },
        { sid: 24, tid: 8, _color: "black" },
        { sid: 8, tid: 24, _color: "black" },
        { sid: 29, tid: 8, _color: "black" },
        { sid: 8, tid: 29, _color: "black" },
        { sid: 8, tid: 8, _color: "black" },
        { sid: 14, tid: 26, _color: "black" },
        { sid: 26, tid: 14, _color: "black" },
        { sid: 24, tid: 26, _color: "black" },
        { sid: 26, tid: 24, _color: "black" },
        { sid: 8, tid: 18, _color: "black" },
        { sid: 18, tid: 8, _color: "black" },
        { sid: 8, tid: 22, _color: "black" },
        { sid: 22, tid: 8, _color: "black" },
        { sid: 25, tid: 26, _color: "black" },
        { sid: 26, tid: 25, _color: "black" },
        { sid: 26, tid: 16, _color: "black" },
        { sid: 16, tid: 26, _color: "black" },
        { sid: 26, tid: 29, _color: "black" },
        { sid: 29, tid: 26, _color: "black" },
        { sid: 26, tid: 18, _color: "black" },
        { sid: 18, tid: 26, _color: "black" },
        { sid: 26, tid: 7, _color: "black" },
        { sid: 7, tid: 26, _color: "black" },
        { sid: 21, tid: 16, _color: "black" },
        { sid: 16, tid: 21, _color: "black" },
        { sid: 16, tid: 2, _color: "black" },
        { sid: 2, tid: 16, _color: "black" },
        { sid: 2, tid: 29, _color: "black" },
        { sid: 2, tid: 2, _color: "black" },
        { sid: 2, tid: 14, _color: "black" },
        { sid: 2, tid: 22, _color: "black" },
        { sid: 2, tid: 7, _color: "black" },
        { sid: 2, tid: 5, _color: "black" },
        { sid: 29, tid: 2, _color: "black" },
        { sid: 29, tid: 27, _color: "black" },
        { sid: 5, tid: 2, _color: "black" },
        { sid: 5, tid: 22, _color: "black" },
        { sid: 5, tid: 26, _color: "black" },
        { sid: 5, tid: 27, _color: "black" },
        { sid: 2, tid: 18, _color: "black" },
        { sid: 2, tid: 26, _color: "black" },
        { sid: 2, tid: 27, _color: "black" },
        { sid: 7, tid: 2, _color: "black" },
        { sid: 7, tid: 22, _color: "black" },
        { sid: 7, tid: 27, _color: "black" },
        { sid: 18, tid: 2, _color: "black" },
        { sid: 18, tid: 22, _color: "black" },
        { sid: 18, tid: 27, _color: "black" },
        { sid: 22, tid: 5, _color: "black" },
        { sid: 22, tid: 2, _color: "black" },
        { sid: 22, tid: 7, _color: "black" },
        { sid: 22, tid: 18, _color: "black" },
        { sid: 22, tid: 26, _color: "black" },
        { sid: 22, tid: 27, _color: "black" },
        { sid: 14, tid: 2, _color: "black" },
        { sid: 14, tid: 27, _color: "black" },
        { sid: 16, tid: 27, _color: "black" },
        { sid: 26, tid: 5, _color: "black" },
        { sid: 26, tid: 2, _color: "black" },
        { sid: 26, tid: 22, _color: "black" },
        { sid: 26, tid: 26, _color: "black" },
        { sid: 26, tid: 27, _color: "black" },
        { sid: 27, tid: 29, _color: "black" },
        { sid: 27, tid: 5, _color: "black" },
        { sid: 27, tid: 2, _color: "black" },
        { sid: 27, tid: 7, _color: "black" },
        { sid: 27, tid: 18, _color: "black" },
        { sid: 27, tid: 22, _color: "black" },
        { sid: 27, tid: 14, _color: "black" },
        { sid: 27, tid: 16, _color: "black" },
        { sid: 27, tid: 26, _color: "black" },
        { sid: 27, tid: 27, _color: "black" },
        { sid: 14, tid: 21, _color: "black" },
        { sid: 21, tid: 14, _color: "black" },
        { sid: 21, tid: 22, _color: "black" },
        { sid: 22, tid: 21, _color: "black" },
        { sid: 22, tid: 28, _color: "black" },
        { sid: 11, tid: 14, _color: "black" },
        { sid: 14, tid: 11, _color: "black" },
        { sid: 26, tid: 8, _color: "black" },
        { sid: 20, tid: 8, _color: "black" },
        { sid: 20, tid: 29, _color: "black" },
        { sid: 10, tid: 29, _color: "black" },
        { sid: 20, tid: 14, _color: "black" },
        { sid: 20, tid: 22, _color: "black" },
        { sid: 8, tid: 26, _color: "black" },
        { sid: 20, tid: 26, _color: "black" },
        { sid: 29, tid: 20, _color: "black" },
        { sid: 8, tid: 20, _color: "black" },
        { sid: 14, tid: 20, _color: "black" },
        { sid: 22, tid: 20, _color: "black" },
        { sid: 26, tid: 20, _color: "black" },
        { sid: 20, tid: 20, _color: "black" },
        { sid: 25, tid: 20, _color: "black" },
        { sid: 10, tid: 20, _color: "black" },
        { sid: 20, tid: 25, _color: "black" },
        { sid: 29, tid: 10, _color: "black" },
        { sid: 20, tid: 10, _color: "black" },
        { sid: 21, tid: 26, _color: "black" },
        { sid: 17, tid: 26, _color: "black" },
        { sid: 10, tid: 26, _color: "black" },
        { sid: 2, tid: 8, _color: "black" },
        { sid: 21, tid: 8, _color: "black" },
        { sid: 13, tid: 8, _color: "black" },
        { sid: 10, tid: 8, _color: "black" },
        { sid: 8, tid: 2, _color: "black" },
        { sid: 28, tid: 2, _color: "black" },
        { sid: 21, tid: 2, _color: "black" },
        { sid: 20, tid: 2, _color: "black" },
        { sid: 25, tid: 2, _color: "black" },
        { sid: 10, tid: 2, _color: "black" },
        { sid: 21, tid: 29, _color: "black" },
        { sid: 13, tid: 29, _color: "black" },
        { sid: 21, tid: 7, _color: "black" },
        { sid: 13, tid: 7, _color: "black" },
        { sid: 20, tid: 7, _color: "black" },
        { sid: 17, tid: 7, _color: "black" },
        { sid: 21, tid: 18, _color: "black" },
        { sid: 20, tid: 18, _color: "black" },
        { sid: 17, tid: 18, _color: "black" },
        { sid: 10, tid: 18, _color: "black" },
        { sid: 21, tid: 5, _color: "black" },
        { sid: 20, tid: 5, _color: "black" },
        { sid: 26, tid: 21, _color: "black" },
        { sid: 8, tid: 21, _color: "black" },
        { sid: 29, tid: 21, _color: "black" },
        { sid: 7, tid: 21, _color: "black" },
        { sid: 2, tid: 21, _color: "black" },
        { sid: 18, tid: 21, _color: "black" },
        { sid: 5, tid: 21, _color: "black" },
        { sid: 21, tid: 21, _color: "black" },
        { sid: 20, tid: 21, _color: "black" },
        { sid: 25, tid: 21, _color: "black" },
        { sid: 17, tid: 21, _color: "black" },
        { sid: 16, tid: 20, _color: "black" },
        { sid: 7, tid: 20, _color: "black" },
        { sid: 2, tid: 20, _color: "black" },
        { sid: 18, tid: 20, _color: "black" },
        { sid: 5, tid: 20, _color: "black" },
        { sid: 21, tid: 20, _color: "black" },
        { sid: 2, tid: 25, _color: "black" },
        { sid: 21, tid: 25, _color: "black" },
        { sid: 10, tid: 25, _color: "black" },
        { sid: 13, tid: 14, _color: "black" },
        { sid: 10, tid: 14, _color: "black" },
        { sid: 13, tid: 16, _color: "black" },
        { sid: 20, tid: 16, _color: "black" },
        { sid: 17, tid: 16, _color: "black" },
        { sid: 28, tid: 22, _color: "black" },
        { sid: 13, tid: 22, _color: "black" },
        { sid: 10, tid: 22, _color: "black" },
        { sid: 26, tid: 17, _color: "black" },
        { sid: 16, tid: 17, _color: "black" },
        { sid: 7, tid: 17, _color: "black" },
        { sid: 18, tid: 17, _color: "black" },
        { sid: 21, tid: 17, _color: "black" },
        { sid: 17, tid: 17, _color: "black" },
        { sid: 26, tid: 10, _color: "black" },
        { sid: 8, tid: 10, _color: "black" },
        { sid: 14, tid: 10, _color: "black" },
        { sid: 22, tid: 10, _color: "black" },
        { sid: 2, tid: 10, _color: "black" },
        { sid: 18, tid: 10, _color: "black" },
        { sid: 13, tid: 10, _color: "black" },
        { sid: 25, tid: 10, _color: "black" },
        { sid: 10, tid: 10, _color: "black" },
        { sid: 8, tid: 13, _color: "black" },
        { sid: 16, tid: 13, _color: "black" },
        { sid: 29, tid: 13, _color: "black" },
        { sid: 14, tid: 13, _color: "black" },
        { sid: 22, tid: 13, _color: "black" },
        { sid: 7, tid: 13, _color: "black" },
        { sid: 13, tid: 13, _color: "black" },
        { sid: 10, tid: 13, _color: "black" },
        { sid: 2, tid: 28, _color: "black" },
        { sid: 12, tid: 29, _color: "black" },
        { sid: 9, tid: 29, _color: "black" },
        { sid: 15, tid: 29, _color: "black" },
        { sid: 28, tid: 29, _color: "black" },
        { sid: 12, tid: 8, _color: "black" },
        { sid: 9, tid: 8, _color: "black" },
        { sid: 15, tid: 8, _color: "black" },
        { sid: 28, tid: 8, _color: "black" },
        { sid: 12, tid: 22, _color: "black" },
        { sid: 9, tid: 22, _color: "black" },
        { sid: 15, tid: 22, _color: "black" },
        { sid: 12, tid: 14, _color: "black" },
        { sid: 9, tid: 14, _color: "black" },
        { sid: 29, tid: 12, _color: "black" },
        { sid: 8, tid: 12, _color: "black" },
        { sid: 22, tid: 12, _color: "black" },
        { sid: 14, tid: 12, _color: "black" },
        { sid: 12, tid: 12, _color: "black" },
        { sid: 13, tid: 12, _color: "black" },
        { sid: 9, tid: 12, _color: "black" },
        { sid: 15, tid: 12, _color: "black" },
        { sid: 28, tid: 12, _color: "black" },
        { sid: 12, tid: 13, _color: "black" },
        { sid: 9, tid: 13, _color: "black" },
        { sid: 15, tid: 13, _color: "black" },
        { sid: 28, tid: 13, _color: "black" },
        { sid: 29, tid: 9, _color: "black" },
        { sid: 8, tid: 9, _color: "black" },
        { sid: 22, tid: 9, _color: "black" },
        { sid: 14, tid: 9, _color: "black" },
        { sid: 12, tid: 9, _color: "black" },
        { sid: 13, tid: 9, _color: "black" },
        { sid: 9, tid: 9, _color: "black" },
        { sid: 15, tid: 9, _color: "black" },
        { sid: 28, tid: 9, _color: "black" },
        { sid: 29, tid: 15, _color: "black" },
        { sid: 8, tid: 15, _color: "black" },
        { sid: 22, tid: 15, _color: "black" },
        { sid: 12, tid: 15, _color: "black" },
        { sid: 13, tid: 15, _color: "black" },
        { sid: 9, tid: 15, _color: "black" },
        { sid: 15, tid: 15, _color: "black" },
        { sid: 28, tid: 15, _color: "black" },
        { sid: 29, tid: 28, _color: "black" },
        { sid: 8, tid: 28, _color: "black" },
        { sid: 12, tid: 28, _color: "black" },
        { sid: 13, tid: 28, _color: "black" },
        { sid: 9, tid: 28, _color: "black" },
        { sid: 15, tid: 28, _color: "black" },
        { sid: 28, tid: 28, _color: "black" },
        { sid: 1, tid: 1, _color: "black" },
        { sid: 2, tid: 1, _color: "black" },
        { sid: 3, tid: 1, _color: "black" },
        { sid: 5, tid: 1, _color: "black" },
        { sid: 7, tid: 1, _color: "black" },
        { sid: 8, tid: 1, _color: "black" },
        { sid: 10, tid: 1, _color: "black" },
        { sid: 11, tid: 1, _color: "black" },
        { sid: 15, tid: 1, _color: "black" },
        { sid: 16, tid: 1, _color: "black" },
        { sid: 18, tid: 1, _color: "black" },
        { sid: 19, tid: 1, _color: "black" },
        { sid: 20, tid: 1, _color: "black" },
        { sid: 21, tid: 1, _color: "black" },
        { sid: 22, tid: 1, _color: "black" },
        { sid: 23, tid: 1, _color: "black" },
        { sid: 25, tid: 1, _color: "black" },
        { sid: 26, tid: 1, _color: "black" },
        { sid: 1, tid: 2, _color: "black" },
        { sid: 3, tid: 2, _color: "black" },
        { sid: 11, tid: 2, _color: "black" },
        { sid: 15, tid: 2, _color: "black" },
        { sid: 19, tid: 2, _color: "black" },
        { sid: 23, tid: 2, _color: "black" },
        { sid: 1, tid: 3, _color: "black" },
        { sid: 2, tid: 3, _color: "black" },
        { sid: 3, tid: 3, _color: "black" },
        { sid: 5, tid: 3, _color: "black" },
        { sid: 7, tid: 3, _color: "black" },
        { sid: 8, tid: 3, _color: "black" },
        { sid: 10, tid: 3, _color: "black" },
        { sid: 11, tid: 3, _color: "black" },
        { sid: 15, tid: 3, _color: "black" },
        { sid: 16, tid: 3, _color: "black" },
        { sid: 18, tid: 3, _color: "black" },
        { sid: 19, tid: 3, _color: "black" },
        { sid: 20, tid: 3, _color: "black" },
        { sid: 21, tid: 3, _color: "black" },
        { sid: 22, tid: 3, _color: "black" },
        { sid: 23, tid: 3, _color: "black" },
        { sid: 25, tid: 3, _color: "black" },
        { sid: 26, tid: 3, _color: "black" },
        { sid: 1, tid: 5, _color: "black" },
        { sid: 3, tid: 5, _color: "black" },
        { sid: 11, tid: 5, _color: "black" },
        { sid: 19, tid: 5, _color: "black" },
        { sid: 1, tid: 7, _color: "black" },
        { sid: 3, tid: 7, _color: "black" },
        { sid: 11, tid: 7, _color: "black" },
        { sid: 19, tid: 7, _color: "black" },
        { sid: 1, tid: 8, _color: "black" },
        { sid: 3, tid: 8, _color: "black" },
        { sid: 11, tid: 8, _color: "black" },
        { sid: 19, tid: 8, _color: "black" },
        { sid: 23, tid: 8, _color: "black" },
        { sid: 1, tid: 11, _color: "black" },
        { sid: 2, tid: 11, _color: "black" },
        { sid: 3, tid: 11, _color: "black" },
        { sid: 5, tid: 11, _color: "black" },
        { sid: 7, tid: 11, _color: "black" },
        { sid: 8, tid: 11, _color: "black" },
        { sid: 11, tid: 11, _color: "black" },
        { sid: 16, tid: 11, _color: "black" },
        { sid: 18, tid: 11, _color: "black" },
        { sid: 19, tid: 11, _color: "black" },
        { sid: 21, tid: 11, _color: "black" },
        { sid: 22, tid: 11, _color: "black" },
        { sid: 23, tid: 11, _color: "black" },
        { sid: 25, tid: 11, _color: "black" },
        { sid: 26, tid: 11, _color: "black" },
        { sid: 1, tid: 18, _color: "black" },
        { sid: 3, tid: 18, _color: "black" },
        { sid: 11, tid: 18, _color: "black" },
        { sid: 15, tid: 18, _color: "black" },
        { sid: 19, tid: 18, _color: "black" },
        { sid: 23, tid: 18, _color: "black" },
        { sid: 1, tid: 21, _color: "black" },
        { sid: 3, tid: 21, _color: "black" },
        { sid: 11, tid: 21, _color: "black" },
        { sid: 19, tid: 21, _color: "black" },
        { sid: 23, tid: 21, _color: "black" },
        { sid: 1, tid: 22, _color: "black" },
        { sid: 3, tid: 22, _color: "black" },
        { sid: 11, tid: 22, _color: "black" },
        { sid: 19, tid: 22, _color: "black" },
        { sid: 23, tid: 22, _color: "black" },
        { sid: 1, tid: 23, _color: "black" },
        { sid: 2, tid: 23, _color: "black" },
        { sid: 3, tid: 23, _color: "black" },
        { sid: 8, tid: 23, _color: "black" },
        { sid: 11, tid: 23, _color: "black" },
        { sid: 16, tid: 23, _color: "black" },
        { sid: 18, tid: 23, _color: "black" },
        { sid: 19, tid: 23, _color: "black" },
        { sid: 21, tid: 23, _color: "black" },
        { sid: 22, tid: 23, _color: "black" },
        { sid: 23, tid: 23, _color: "black" },
        { sid: 25, tid: 23, _color: "black" },
        { sid: 26, tid: 23, _color: "black" },
        { sid: 1, tid: 16, _color: "black" },
        { sid: 3, tid: 16, _color: "black" },
        { sid: 11, tid: 16, _color: "black" },
        { sid: 19, tid: 16, _color: "black" },
        { sid: 23, tid: 16, _color: "black" },
        { sid: 1, tid: 19, _color: "black" },
        { sid: 2, tid: 19, _color: "black" },
        { sid: 3, tid: 19, _color: "black" },
        { sid: 5, tid: 19, _color: "black" },
        { sid: 7, tid: 19, _color: "black" },
        { sid: 8, tid: 19, _color: "black" },
        { sid: 11, tid: 19, _color: "black" },
        { sid: 16, tid: 19, _color: "black" },
        { sid: 18, tid: 19, _color: "black" },
        { sid: 19, tid: 19, _color: "black" },
        { sid: 21, tid: 19, _color: "black" },
        { sid: 22, tid: 19, _color: "black" },
        { sid: 23, tid: 19, _color: "black" },
        { sid: 25, tid: 19, _color: "black" },
        { sid: 26, tid: 19, _color: "black" },
        { sid: 1, tid: 25, _color: "black" },
        { sid: 3, tid: 25, _color: "black" },
        { sid: 11, tid: 25, _color: "black" },
        { sid: 19, tid: 25, _color: "black" },
        { sid: 23, tid: 25, _color: "black" },
        { sid: 1, tid: 26, _color: "black" },
        { sid: 3, tid: 26, _color: "black" },
        { sid: 11, tid: 26, _color: "black" },
        { sid: 19, tid: 26, _color: "black" },
        { sid: 23, tid: 26, _color: "black" },
        { sid: 1, tid: 10, _color: "black" },
        { sid: 3, tid: 10, _color: "black" },
        { sid: 1, tid: 15, _color: "black" },
        { sid: 2, tid: 15, _color: "black" },
        { sid: 3, tid: 15, _color: "black" },
        { sid: 18, tid: 15, _color: "black" },
        { sid: 1, tid: 20, _color: "black" },
        { sid: 3, tid: 20, _color: "black" },
        { sid: 6, tid: 18, _color: "black" },
        { sid: 30, tid: 18, _color: "black" },
        { sid: 1, tid: 29, _color: "black" },
        { sid: 17, tid: 29, _color: "black" },
        { sid: 19, tid: 29, _color: "black" },
        { sid: 3, tid: 29, _color: "black" },
        { sid: 30, tid: 29, _color: "black" },
        { sid: 6, tid: 29, _color: "black" },
        { sid: 19, tid: 15, _color: "black" },
        { sid: 16, tid: 15, _color: "black" },
        { sid: 5, tid: 15, _color: "black" },
        { sid: 21, tid: 15, _color: "black" },
        { sid: 25, tid: 15, _color: "black" },
        { sid: 24, tid: 15, _color: "black" },
        { sid: 17, tid: 15, _color: "black" },
        { sid: 26, tid: 15, _color: "black" },
        { sid: 10, tid: 15, _color: "black" },
        { sid: 7, tid: 15, _color: "black" },
        { sid: 30, tid: 15, _color: "black" },
        { sid: 6, tid: 15, _color: "black" },
        { sid: 6, tid: 2, _color: "black" },
        { sid: 24, tid: 2, _color: "black" },
        { sid: 30, tid: 2, _color: "black" },
        { sid: 17, tid: 2, _color: "black" },
        { sid: 17, tid: 5, _color: "black" },
        { sid: 6, tid: 5, _color: "black" },
        { sid: 15, tid: 5, _color: "black" },
        { sid: 30, tid: 5, _color: "black" },
        { sid: 10, tid: 5, _color: "black" },
        { sid: 15, tid: 16, _color: "black" },
        { sid: 30, tid: 16, _color: "black" },
        { sid: 6, tid: 16, _color: "black" },
        { sid: 10, tid: 16, _color: "black" },
        { sid: 17, tid: 22, _color: "black" },
        { sid: 30, tid: 22, _color: "black" },
        { sid: 6, tid: 22, _color: "black" },
        { sid: 15, tid: 25, _color: "black" },
        { sid: 6, tid: 25, _color: "black" },
        { sid: 30, tid: 25, _color: "black" },
        { sid: 17, tid: 25, _color: "black" },
        { sid: 1, tid: 30, _color: "black" },
        { sid: 30, tid: 30, _color: "black" },
        { sid: 16, tid: 30, _color: "black" },
        { sid: 19, tid: 30, _color: "black" },
        { sid: 22, tid: 30, _color: "black" },
        { sid: 7, tid: 30, _color: "black" },
        { sid: 24, tid: 30, _color: "black" },
        { sid: 26, tid: 30, _color: "black" },
        { sid: 14, tid: 30, _color: "black" },
        { sid: 25, tid: 30, _color: "black" },
        { sid: 29, tid: 30, _color: "black" },
        { sid: 15, tid: 30, _color: "black" },
        { sid: 8, tid: 30, _color: "black" },
        { sid: 18, tid: 30, _color: "black" },
        { sid: 21, tid: 30, _color: "black" },
        { sid: 5, tid: 30, _color: "black" },
        { sid: 17, tid: 1, _color: "black" },
        { sid: 14, tid: 1, _color: "black" },
        { sid: 29, tid: 1, _color: "black" },
        { sid: 24, tid: 1, _color: "black" },
        { sid: 6, tid: 1, _color: "black" },
        { sid: 30, tid: 1, _color: "black" },
        { sid: 14, tid: 17, _color: "black" },
        { sid: 25, tid: 17, _color: "black" },
        { sid: 2, tid: 17, _color: "black" },
        { sid: 29, tid: 17, _color: "black" },
        { sid: 22, tid: 17, _color: "black" },
        { sid: 8, tid: 17, _color: "black" },
        { sid: 19, tid: 17, _color: "black" },
        { sid: 1, tid: 17, _color: "black" },
        { sid: 15, tid: 17, _color: "black" },
        { sid: 24, tid: 17, _color: "black" },
        { sid: 6, tid: 17, _color: "black" },
        { sid: 5, tid: 17, _color: "black" },
        { sid: 3, tid: 17, _color: "black" },
        { sid: 10, tid: 17, _color: "black" },
        { sid: 15, tid: 26, _color: "black" },
        { sid: 30, tid: 26, _color: "black" },
        { sid: 6, tid: 26, _color: "black" },
        { sid: 17, tid: 8, _color: "black" },
        { sid: 6, tid: 8, _color: "black" },
        { sid: 30, tid: 8, _color: "black" },
        { sid: 15, tid: 10, _color: "black" },
        { sid: 19, tid: 10, _color: "black" },
        { sid: 21, tid: 10, _color: "black" },
        { sid: 24, tid: 10, _color: "black" },
        { sid: 17, tid: 10, _color: "black" },
        { sid: 16, tid: 10, _color: "black" },
        { sid: 5, tid: 10, _color: "black" },
        { sid: 7, tid: 10, _color: "black" },
        { sid: 6, tid: 10, _color: "black" },
        { sid: 17, tid: 14, _color: "black" },
        { sid: 19, tid: 14, _color: "black" },
        { sid: 1, tid: 14, _color: "black" },
        { sid: 6, tid: 14, _color: "black" },
        { sid: 30, tid: 14, _color: "black" },
        { sid: 3, tid: 14, _color: "black" },
        { sid: 24, tid: 21, _color: "black" },
        { sid: 6, tid: 21, _color: "black" },
        { sid: 15, tid: 21, _color: "black" },
        { sid: 30, tid: 21, _color: "black" },
        { sid: 10, tid: 21, _color: "black" },
        { sid: 17, tid: 3, _color: "black" },
        { sid: 14, tid: 3, _color: "black" },
        { sid: 29, tid: 3, _color: "black" },
        { sid: 6, tid: 3, _color: "black" },
        { sid: 24, tid: 3, _color: "black" },
        { sid: 29, tid: 19, _color: "black" },
        { sid: 14, tid: 19, _color: "black" },
        { sid: 15, tid: 19, _color: "black" },
        { sid: 30, tid: 19, _color: "black" },
        { sid: 10, tid: 19, _color: "black" },
        { sid: 24, tid: 19, _color: "black" },
        { sid: 6, tid: 19, _color: "black" },
        { sid: 17, tid: 19, _color: "black" },
        { sid: 15, tid: 7, _color: "black" },
        { sid: 6, tid: 7, _color: "black" },
        { sid: 30, tid: 7, _color: "black" },
        { sid: 10, tid: 7, _color: "black" },
        { sid: 15, tid: 24, _color: "black" },
        { sid: 19, tid: 24, _color: "black" },
        { sid: 21, tid: 24, _color: "black" },
        { sid: 17, tid: 24, _color: "black" },
        { sid: 2, tid: 24, _color: "black" },
        { sid: 10, tid: 24, _color: "black" },
        { sid: 1, tid: 24, _color: "black" },
        { sid: 3, tid: 24, _color: "black" },
        { sid: 6, tid: 24, _color: "black" },
        { sid: 30, tid: 24, _color: "black" },
        { sid: 19, tid: 6, _color: "black" },
        { sid: 5, tid: 6, _color: "black" },
        { sid: 29, tid: 6, _color: "black" },
        { sid: 8, tid: 6, _color: "black" },
        { sid: 17, tid: 6, _color: "black" },
        { sid: 2, tid: 6, _color: "black" },
        { sid: 7, tid: 6, _color: "black" },
        { sid: 1, tid: 6, _color: "black" },
        { sid: 14, tid: 6, _color: "black" },
        { sid: 6, tid: 6, _color: "black" },
        { sid: 25, tid: 6, _color: "black" },
        { sid: 21, tid: 6, _color: "black" },
        { sid: 26, tid: 6, _color: "black" },
        { sid: 22, tid: 6, _color: "black" },
        { sid: 24, tid: 6, _color: "black" },
        { sid: 16, tid: 6, _color: "black" },
        { sid: 15, tid: 6, _color: "black" },
        { sid: 18, tid: 6, _color: "black" },
        { sid: 30, tid: 6, _color: "black" },
        { sid: 3, tid: 6, _color: "black" },
        { sid: 10, tid: 6, _color: "black" },
        { sid: 4, tid: 23, _color: "black" },
        { sid: 28, tid: 1, _color: "black" },
        { sid: 20, tid: 15, _color: "black" },
        { sid: 1, tid: 28, _color: "black" },
        { sid: 4, tid: 4, _color: "black" },
        { sid: 15, tid: 20, _color: "black" },
      ],
      nodeSize: 10,
      canvas: false,
      // customForces: {('collide',d3.forceCollide().radius(60).iterations(2))}
    };
  },
  computed: {
    options() {
      return {
        force: 3000,
        size: { w: 1000, h: 1000 },
        nodeSize: this.nodeSize,
        nodeLabels: true,
        canvas: this.canvas,
        linkWidth: 2,
        strLinks: true,
      };
    },
  },
  methods: {
    lcb(link) {
      link._svgAttrs = {
        "marker-end": "url(#m-end)",
        "marker-start": "url(#m-start)",
      };
      return link;
    },
  },
};
//...
</script>

<style scoped>
@import "/../node_modules/vue-d3-network/dist/vue-d3-network.css";
@import url("https://fonts.googleapis.com/css?family=PT+Sans");

body {
  font-family: "PT Sans", sans-serif;
  background-color: #eee;
}
.title {
  position: absolute;
  text-align: center;
  left: 2em;
}
h1,
a {
  color: #1aad8d;
  text-decoration: none;
}

ul.menu {
  list-style: none;
  position: absolute;
  z-index: 100;
  min-width: 20em;
  text-align: left;
}
ul.menu li {
  margin-top: 1em;
  position: relative;
}
.node {
  color: #1aad8d;
}
.greenNode {
  color: #1aad8d;
}
#m-end path,
#m-start {
  fill: rgba(18, 120, 98, 0.8);
}
</style>